
rem PATH="./output/"
set CURRENT_DIR=%CD%
set OUTPUT_DIR=%CURRENT_DIR%\output
set PROJECT_DIR=C:\Projects\wm

@echo on

Excel2Binary charTable.xlsx %OUTPUT_DIR%\charTable.bytes -head -indexer
Excel2Binary objectTable.xlsx %OUTPUT_DIR%\objectTable.bytes -head -indexer

cd %OUTPUT_DIR%
copy *.bytes %PROJECT_DIR%\Assets\Resources\Data\*.bytes
copy *.cs %PROJECT_DIR%\Assets\Script\AutoGenerated\*.cs

pause